_include_yml: orthrus_non_snooped

training:
  encoder:
    used_methods: tgn,hyperbolic_transformer
    hyperbolic_transformer:
      trans_num_layers: 2
      trans_num_heads: 4
      trans_dropout: 0.3
      gnn_num_layers: 0
      gnn_dropout: 0.0
      graph_weight: 0.0
      k: 1.0
      attention_type: full
      power_k: 2
      use_bn: True
      use_residual: True
