_include_yml: orthrus_temporal_contrastive

batching:
  intra_graph_batching:
    tgn_last_neighbor:
      tgn_neighbor_size: 15

evaluation:
  used_method: node_evaluation
  best_model_selection: best_adp
  node_evaluation:
    threshold_method: max_val_loss
    use_dst_node_loss: True
    use_kmeans: True
    kmeans_top_K: 30
